# Generated by Django 3.1.7 on 2021-07-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_following_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
